### ISSUE TITLE
Error when trying to unzip Child_Data.zip

### ISSUE THREAD

**Issue by vkouam** [MAli-Farooq/ChildGAN#1]
Hello, 

thank you very much for your great work. 

I have already downloaded the images from the Google Drive [link](https://drive.google.com/drive/folders/11f6kiBsg4-yh9xfNQGJGrsOEmLJ2dzaw) in your repo three times. But I still get the following error when I try to extract the images from one of the three Child_Data zip files [here](https://drive.google.com/drive/folders/11f6kiBsg4-yh9xfNQGJGrsOEmLJ2dzaw):

![Unzip_error](https://github.com/MAli-Farooq/ChildGAN/assets/71090181/d8e71ef3-0ae5-40bb-8a00-e456bfac909e)

Would you please have any tips on how I can access the images?

I look forward to your feedback.
Kind regards

**Comment by MAli-Farooq** [comment]
Hi,

Thanks for letting me know about this. I will recheck the zip files and get back to you.

In the mean time please try using 7 zip software for uncompressing the files and let me know if that worked.

Thank you

**Comment by MAli-Farooq** [comment]
Hi,

Thanks for letting me know about this. I will recheck the zip files and get back to you.

In the mean time please try using 7 zip software for uncompressing the files and let me know if that worked.

I have checked using 7 zip software for uncompressing the files and it is working.

So you can try that as well.

Thank you

**Comment by vkouam** [comment]
Hi @MAli-Farooq , 

thank you for you quick response. I tried to uncompress the files in Child_Data with 7-ZIP and it worked indeed.

Thank you for the hint :)

Kindly
